[project]
name = "airflow-jaffleshop"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.1.7",
    "astronomer-cosmos[dbt-snowflake]>=1.13.0",
    "dbt-core>=1.11.4",
    "dbt-snowflake>=1.11.2",
]
